package de.debuglevel.addressgeocoding.geocoding.photon


import com.fasterxml.jackson.annotation.JsonProperty

// Note: Generated by https://plugins.jetbrains.com/plugin/9960-json-to-kotlin-class-jsontokotlinclass- extension with Jackson annotations enabled
data class ResultSet(
    @JsonProperty("features")
    val features: List<Feature>,
    @JsonProperty("type")
    val type: String
)